name: Edit README upon branch creation
run-name: ${{ github.actor }} adjusting README
on:
  create

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Modify README.md
        run: |
          echo "![${{ github.ref_name }}](https://github.com/LEMMIIX/masterutils/tree/${{ github.ref_name }})" >> README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
